version: "3.8"

services:
  database:
    env_file: ./.env
    volumes:
    - postgresdb:/var/lib/postgress
    image: postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
  server:
    depends_on:
      - database
    build: ./server
    env_file: ./.env
    restart: on-failure
    ports:
      - 3333:3333
    environment:
      NODE_ENV: $NODE_ENV
      DATABASE_URL: $DATABASE_DOCKER_URL
      MAILSERVER_URL: $MAILSERVER_URL
    stdin_open: true
    tty: true
  web:
    env_file: ./web/.env.local
    depends_on:
      - server
    build: ./web
    restart: on-failure
    ports:
      - 4173:4173
    expose:
      - 4173
    environment:
      NODE_ENV: production
      VITE_API_URL: $VITE_API_URL
    stdin_open: true
    tty: true


volumes:
  postgresdb:


    
    
  